# Generated by Django 2.1.7 on 2019-05-08 06:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('email', models.CharField(default='', max_length=200)),
                ('number', models.CharField(default='', max_length=200)),
                ('fileno', models.CharField(default='', max_length=10)),
                ('doa', models.CharField(default='', max_length=200)),
                ('cdoctor', models.CharField(default='', max_length=200)),
                ('timetable', models.CharField(default='', max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('email', models.CharField(default='', max_length=200)),
                ('number', models.CharField(default='', max_length=200)),
                ('message', models.CharField(default='', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='DoctorProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('image', models.FileField(upload_to='user_image')),
                ('experience1', models.CharField(default='', max_length=200)),
                ('experience2', models.CharField(default='', max_length=200)),
                ('experience3', models.CharField(default='', max_length=200)),
                ('experience4', models.CharField(default='', max_length=200)),
                ('experience5', models.CharField(default='', max_length=200)),
                ('age', models.CharField(default='', max_length=200)),
                ('dob', models.CharField(default='', max_length=200)),
                ('department', models.CharField(default='', max_length=200)),
                ('qualification1', models.CharField(default='', max_length=500)),
                ('qualification2', models.CharField(default='', max_length=500)),
                ('qualification3', models.CharField(default='', max_length=500)),
                ('qualification4', models.CharField(default='', max_length=500)),
                ('designation', models.CharField(default='', max_length=200)),
                ('number', models.CharField(default='', max_length=200)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('mobile', models.CharField(max_length=200)),
                ('image', models.FileField(upload_to='user_image')),
                ('fileno', models.CharField(default='', max_length=200)),
                ('age', models.CharField(default='', max_length=200)),
                ('dob', models.CharField(default='', max_length=200)),
                ('issue', models.CharField(default='', max_length=200)),
                ('pastissue', models.CharField(default='', max_length=200)),
                ('prescription', models.CharField(default='', max_length=200)),
                ('bill', models.FileField(default='', upload_to='user_image')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('image', models.FileField(upload_to='user_image')),
                ('sid', models.CharField(default='', max_length=200)),
                ('age', models.CharField(default='', max_length=200)),
                ('dob', models.CharField(default='', max_length=200)),
                ('department', models.CharField(default='', max_length=200)),
                ('qualification', models.CharField(default='', max_length=200)),
                ('designation', models.CharField(default='', max_length=200)),
                ('number', models.CharField(default='', max_length=200)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('p', 'patient'), ('s', 'staff'), ('d', 'doctor')], default='p', max_length=200)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
