# Generated by Django 2.1.7 on 2019-05-08 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='number',
            new_name='subject',
        ),
        migrations.RemoveField(
            model_name='doctorprofile',
            name='age',
        ),
        migrations.RemoveField(
            model_name='doctorprofile',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='doctorprofile',
            name='experience4',
        ),
        migrations.RemoveField(
            model_name='doctorprofile',
            name='experience5',
        ),
        migrations.RemoveField(
            model_name='doctorprofile',
            name='qualification4',
        ),
    ]
